### ISSUE TITLE
There are (a lot of) error in the codes

### ISSUE THREAD

**Issue by Brodvd** [Audio-AGI/FlowSep#2]
Hello, I installed FlowSep and run the file  `lass_inference.py`  like here:
```shell
python3 lass_inference.py --text 'text_of_the_audio'  --audio 'path_to_the_audio'
```
but I had this error:
```shell
Traceback (most recent call last):
  File "C:\Users\User\Documenti\audioagi\FlowSep\lass_inference.py", line 132, in <module>
    parser.add_argument(
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\argparse.py", line 1418, in add_argument
    action = action_class(**kwargs)
TypeError: _StoreFalseAction.__init__() got an unexpected keyword argument 'type'
```
anyone could tell me where I mistook?
Thanks

**Comment by Brodvd** [comment]
maybe the problem is resolved deleting  `type=bool`  like here:
```shell
parser.add_argument(
        "-m",
        "--no_mixed",
        action='store_false',
        help="saving the mixed waveform as well",
```

**Comment by Brodvd** [comment]
Resolved, for any see my fork: https://github.com/Brodvd/FlowSep/tree/My-laptop

**Comment by noob3004** [comment]
Hello, I found that its performance was not good and duration is fixed 10s, what do you think about it?

**Comment by Brodvd** [comment]
Hi @noob3004 yes the performance was not good because the original code worked with a GPU Nvidia while my fork work with a CPU (I don't have a Nvidia).
The duration Is fixed 10s but you can change It in the file `lass_config/2channel_flow.yaml` but if you change the duration of the input you will change the also the size of the spectrogram and I don't know how to do.

**Comment by noob3004** [comment]
> Hi @noob3004 yes the performance was not good because the original code worked with a GPU Nvidia while my fork work with a CPU (I don't have a Nvidia). The duration Is fixed 10s but you can change It in the file `lass_config/2channel_flow.yaml` but if you change the duration of the input you will change the also the size of the spectrogram and I don't know how to do.

In fact, I have Nvidia gpu and run it, But I found that my real voice have been damp in all freq. Very terrible I think.
The 10s is fixed because of Model's shape setting, I think we can't change it and it will be needed to be retrain for new shape.

**Comment by Brodvd** [comment]
Well the output has a quality of 16000 Hz, I think that It was done because a few datasets were 16000 Hz. 
Anyway If you want to separate a voice is better any other separation stem model

**Comment by noob3004** [comment]
Maybe you're right. I wanna a model that can deal with aircraft,car,speech and other background, they are not traditional. Do you have some advice for it?

**Comment by Brodvd** [comment]
Well, unfortunatly the Better that I know Is Flow Sep, there also the old [Audio Sep](https://github.com/Audio-AGI/AudioSep) but is the same about problems. Maybe this link about Flow Sep help you: https://www.aimodels.fyi/papers/arxiv/flowsep-language-queried-sound-separation-rectified-flow

**Comment by noob3004** [comment]
I tried this model and found that there are lots of leaking in the second half and other event. Maybe both of them not avaliable.

**Comment by Brodvd** [comment]
These models are very different respect the stems-separation models, but maybe will be interesting a future model inspired at Flow Sep and Audio Sep.
We hope!

**Comment by yyua8222** [comment]
> maybe the problem is resolved deleting `type=bool` like here:
> 
> ```shell
> parser.add_argument(
>         "-m",
>         "--no_mixed",
>         action='store_false',
>         help="saving the mixed waveform as well",
> ```

Hi, the code seems working fine on various systems and machines, please make sure to use the correct version of each dependency.

**Comment by yyua8222** [comment]
> Maybe you're right. I wanna a model that can deal with aircraft,car,speech and other background, they are not traditional. Do you have some advice for it?

Hi, our model is mainly trained on general audio datasets such as AudioCaps and WavCaps, hence, it might face bad performance on speech and other special audio events. You can try to fine-tune the model on the particular dataset.

**Comment by noob3004** [comment]
> > Maybe you're right. I wanna a model that can deal with aircraft,car,speech and other background, they are not traditional. Do you have some advice for it?
> 
> Hi, our model is mainly trained on general audio datasets such as AudioCaps and WavCaps, hence, it might face bad performance on speech and other special audio events. You can try to fine-tune the model on the particular dataset.

Thanks a lot, I will try it.
